name: Docker

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run all
      run: |
        cd docker
        docker-compose up --build
