name: MacOS Cpp

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-10.15]
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: komiya-atsushi/action-enforce-timeout-minutes@v1.0.0
    - name: Configure
      run: cmake -S . -Bbuild
    - name: Build
      run: cmake --build build --target all -v
    - name: Test
      run: cd build && ctest --verbose
    - name: Install
      run: cmake --build build --target install -v -- DESTDIR=install
      continue-on-error: true
