name: Ubuntu Cpp

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: komiya-atsushi/action-enforce-timeout-minutes@v1.0.0
    - name: Configure
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=Maintainer
    - name: Build and test
      run: cmake --build build --config Maintainer --target all -v
