name: Ubuntu Cpp

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: cmake -S . -Bbuild -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Maintainer
    - name: Build
      run: cmake --build build --config Maintainer --target all -v
    - name: Test
      run: cd build && ctest --verbose
    - name: Install
      run: cmake --build build --config Maintainer --target install -v -- DESTDIR=install
