name: Ubuntu Cpp

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: komiya-atsushi/action-enforce-timeout-minutes@v1.0.0
    - name: Configure
      run: cmake -S . -Bbuild
    - name: Build
      run: cmake --build build --target all -v
    - name: Test
      run: cd build && ctest --verbose
    - name: Install
      run: cmake --build build --target install -v -- DESTDIR=install
    - name: clang-format
      uses: RafikFarhad/clang-format-github-action@v1.0.1
      with:
        sources: "lemon/**/*.h,lemon/**/*.cc,test/**/*.cc,test/**/*.h,demo/**/*.cc,demo/**/*.h,tools/**/*.cc,tools/**/*.h"
        style: file
