name: Windows MinGW

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  build:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: komiya-atsushi/action-enforce-timeout-minutes@v1.0.0
    - name: Check cmake
      run: cmake --version
    - name: Configure
      run: cmake -S. -Bbuild -G "MinGW Makefiles"
    - name: Build
      run: cmake --build build --config Release --target all -v
    - name: Test
      run: cd build && ctest --verbose
