name: Windows MSVC

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cxx_std: [11, 17, 20]
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - uses: komiya-atsushi/action-enforce-timeout-minutes@v1.0.0
    - name: Check cmake
      run: cmake --version
    - name: Configure
      run: cmake -S. -Bbuild -G "Visual Studio 16 2019" -DLEMON_CXX_STANDARD=${{ matrix.cxx_std }}
    - name: Build
      run: cmake --build build --config Release --target ALL_BUILD -- /verbosity:normal /maxcpucount
    - name: Test
      run: cmake --build build --config Release --target RUN_TESTS -- /verbosity:normal /maxcpucount
    - name: Install
      run: cmake --build build --config Release --target INSTALL -- /verbosity:normal /maxcpucount
